package Interfaces;

import EstructurasDeDatos.Grafo;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author danieldangelo
 */
public class InterfazLaberinto extends javax.swing.JFrame {
    Grafo grafo;

    /**
     * Creates new form InterfazLaberinto
     */
    public InterfazLaberinto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LaberintoGrafico = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        WallFollowerBtn = new javax.swing.JButton();
        DfsBtn = new javax.swing.JButton();
        BfsBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CerrarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout LaberintoGraficoLayout = new javax.swing.GroupLayout(LaberintoGrafico);
        LaberintoGrafico.setLayout(LaberintoGraficoLayout);
        LaberintoGraficoLayout.setHorizontalGroup(
            LaberintoGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        LaberintoGraficoLayout.setVerticalGroup(
            LaberintoGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(LaberintoGrafico);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 56, 484, 328));

        jLabel1.setText("Laberinto generado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 22, -1, -1));

        WallFollowerBtn.setText("Wall Follower");
        WallFollowerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WallFollowerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(WallFollowerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        DfsBtn.setText("DFS");
        DfsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DfsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DfsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, -1, -1));

        BfsBtn.setText("BFS");
        BfsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BfsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BfsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        jLabel2.setText("Métodos de resolución:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel3.setText("Tiempo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jLabel4.setText("Tiempo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, -1, -1));

        jLabel5.setText("Tiempo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));

        CerrarBtn.setText("Cerrar");
        CerrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CerrarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DfsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DfsBtnActionPerformed
        //validación: Si el panel contiene un laberinto, realizar la busqueda por Dfs, de lo contrario, imprimir "No existe nigun laberinto"
    }//GEN-LAST:event_DfsBtnActionPerformed

    private void WallFollowerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WallFollowerBtnActionPerformed
        // validación: Si el panel contiene un laberinto, realizar la busqueda por Wall follower, de lo contrario, imprimir "No existe nigun laberinto"
    }//GEN-LAST:event_WallFollowerBtnActionPerformed

    private void BfsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BfsBtnActionPerformed
        // validación: Si el panel contiene un laberinto, realizar la busqueda por Bfs, de lo contrario, imprimir "No existe nigun laberinto"
    }//GEN-LAST:event_BfsBtnActionPerformed

    private void CerrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CerrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazLaberinto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BfsBtn;
    private javax.swing.JButton CerrarBtn;
    private javax.swing.JButton DfsBtn;
    private javax.swing.JPanel LaberintoGrafico;
    private javax.swing.JButton WallFollowerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
